using System.ComponentModel.DataAnnotations; // Provides attributes for validation (like [Required])
using System.ComponentModel; // Provides attributes for customizing display names
using Microsoft.Extensions.Hosting; // Namespace used for hosting extensions, but not needed in this class

namespace TabloidFullStack.Models
{
    // This class represents a Comment entity in the system
    public class Comment
    {
        // Primary key for the Comment, automatically generated by the database
        public int Id { get; set; }

        // The subject of the comment, required (cannot be null or empty)
        [Required]
        public string Subject { get; set; }

        // The content of the comment, required but can be null (hence the question mark for nullable types)
        [Required]
        public string? Content { get; set; }

        // Represents the author's UserProfile ID (foreign key), displayed as "Author" in forms
        [DisplayName("Author")]
        public int UserProfileId { get; set; }

        // Navigation property to the UserProfile entity (allows accessing the related UserProfile data)
        // Nullable, meaning there may be no UserProfile object linked (e.g., if not loaded from the database)
        public UserProfile? UserProfile { get; set; }

        // Displayed as "Created on" in forms; stores the date and time when the comment was created
        [DisplayName("Created on")]
        public DateTime CreateDateTime { get; set; }

        // Navigation property to the related Post entity (allows accessing the related Post data)
        // Nullable, meaning the Post object may not be linked or loaded
        public Post? Post { get; set; }

        // Represents the Post's ID (foreign key) that the comment belongs to
        public int PostId { get; set; }
    }
}
